import type { Metadata } from 'next';

import './globals.css';
import { monts } from './fonts/config';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${monts.className} antialiased bg-[#0C0A10] text-white`}
      >
        {children}
      </body>
    </html>
  );
}
